---
- name: Add required permissions to data and docker_apps directories
  ansible.builtin.file:
    path: "{{ item }}"
    recurse: true
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
  loop:
    - "{{ data_dir }}"
    - "{{ docker_dir }}/filebrowser"
    - "{{ docker_dir }}/overseerr"
    - "{{ docker_dir }}/portainer"
    - "{{ docker_dir }}/prowlarr"
    - "{{ docker_dir }}/qbittorrent"
    - "{{ docker_dir }}/radarr"
    - "{{ docker_dir }}/sonarr"
    - "{{ docker_dir }}/watchtower"
    - "{{ docker_dir }}/webtop"
    - "{{ docker_dir }}/aria2"
