---
- name: Create dashdot container
  community.docker.docker_container:
    name: dashdot
    image: mauricenino/dashdot:latest
    restart_policy: unless-stopped
    state: started
    pull: true
    privileged: true
    ports:
      - "3000:3000" # view
      - "3001:3001" # server
      - "3002:3002" # docs
    env:
       DASHDOT_ENABLE_CPU_TEMPS: "true"
       DASHDOT_SPEED_TEST_FROM_PATH: "/app/speedtest_result"
       DASHDOT_SHOW_DASH_VERSION: "none"
    volumes:
      - "/:/mnt/host:ro"


