---
- name: Create duplicati container
  community.docker.docker_container:
    name: duplicati
    image: lscr.io/linuxserver/duplicati:latest
    pull: true
    state: started
    ports:
      - 8200:8200
    restart_policy: unless-stopped
    volumes:
      - "{{ docker_dir }}/duplicati/config:/config"
      - "{{ docker_dir }}/duplicati/backups:/backups"
      - "/:/source"
    env:
      PUID: "0"
      PGID: "0"
      TZ: "{{ timezone }}"
