---
- name: Create guacamole container
  community.docker.docker_container:
    name: guacamole
    image: maxwaldorf/guacamole
    pull: true
    state: started
    ports:
      - "8877:8080"
    restart_policy: unless-stopped
    volumes:
      - "{{ docker_dir }}/guacamole/config:/config"
