- name: Create overseerr container
  community.docker.docker_container:
    name: overseerr
    image: sctx/overseerr
    pull: true
    state: started
    restart_policy: unless-stopped
    ports:
      - "5055:5055"
    env:
      LOG_LEVEL: "debug"
      PORT: "5055"
      TZ: "{{ timezone }}"  
    volumes:
      - "{{ docker_dir }}/overseerr/appdata/config:/app/config"