---
- name: Create qbittorrent container
  community.docker.docker_container:
    name: qbittorrent
    image: linuxserver/qbittorrent
    restart_policy: unless-stopped
    state: started
    ports:
      - "6881:6881"
      - "6881:6881/udp"
      - "8080:8080"
    volumes:
      - "{{ docker_dir }}/qbittorrent/config:/config"
      - "{{ data_dir }}/torrents:/downloads"
      - "{{ docker_dir }}/qbittorrent/vuetorrent:/vuetorrent"
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ timezone }}"
 
