---
- name: Get latest release of vuetorrent
 community.general.github_release:
    user: "WDaan"
    repo: "VueTorrent"
    action: latest_release
  register: latest_release

- name: Unzip vuetorrent
  ansible.builtin.unarchive:
    src: "https://github.com/WDaan/VueTorrent/releases/download/{{ latest_release.tag }}/vuetorrent.zip"
    dest: "{{ docker_dir }}/qbittorrent"
    creates: "{{ docker_dir }}/qbittorrent/vuetorrent"
    remote_src: true
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"

- name: Create qbittorrent container
  community.docker.docker_container:
    name: qbittorrent
    image: linuxserver/qbittorrent
    restart_policy: unless-stopped
    state: started
    ports:
      - "6881:6881"
      - "6881:6881/udp"
      - "8080:8080"
    volumes:
      - "{{ docker_dir }}/qbittorrent/config:/config"
      - "{{ data_dir }}/torrents:/downloads"
      - "{{ docker_dir }}/qbittorrent/vuetorrent:/vuetorrent"
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ timezone }}"

 
