---
- name: Create radarr container
  community.docker.docker_container:
    name: radarr
    image: lscr.io/linuxserver/radarr
    pull: true
    state: started
    restart_policy: unless-stopped
    ports:
      - "7878:7878"
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
      TZ: "{{ timezone }}"
      DOCKER_MODS: ghcr.io/gilbn/theme.park:radarr
    volumes:
      - "{{ docker_dir }}/radarr/config:/config"
      - "{{ data_dir }}:/data"
