---
- name: Create requestrr container
  community.docker.docker_container:
    name: requestrr
    image: darkalfx/requestrr
    pull: true
    state: started
    restart_policy: unless-stopped
    ports:
      - "4545:4545"
    volumes:
      - "{{ docker_dir }}/requestrr:/root/config"

 
