---
- name: Create unmanic container
  community.docker.docker_container:
    name: unmanic
    image: josh5/unmanic:latest
    pull: true
    state: started
    restart_policy: unless-stopped
    ports:
     -  8888:8888
    env:
      PUID: "{{ puid }}"
      PGID: "{{ pgid }}"
    volumes:
      - "{{ docker_dir }}/unmanic/config:/config"
      - "{{ data_dir }}/media/movies:/library/movies"
      - "{{ data_dir }}/media/tv:/library/tv"
      - /tmp:/tmp/unmanic

