---
- name: Create uptime kuma container
  community.docker.docker_container:
    name: uptime_kuma
    image: louislam/uptime-kuma:1
    pull: true
    state: started
    restart_policy: unless-stopped
    ports:
      - "3003:3001"
    volumes:
      - "{{ docker_dir }}/uptime_kuma/data:/app/data"
    security_opts:
      - no-new-privileges:true

